### PR TITLE
Fix a bunch of issues

### LINKED ISSUE #23: Does not wrap a series of whitespace
```js
wrap('   ', 2, { trim: false })
'   '   // actual
'  \n ' // expected
```

Adding `hard` does not change the behaviour.

### LINKED ISSUE #24: Difference in output between 2.1.0 and 3.0.1
I have the following minimal test case:
```js
'use strict'

const wrap = require('wrap-ansi');
const chalk = require('chalk');
const srcString = chalk.blue('  1  2  ');

console.log('"' + wrap(srcString, 20, {hard: true}) + '"');
console.log('"' + wrap(srcString, 20, {hard: true, trim: false}) + '"');
```

Note that srcString has 2 spaces before, between and after the numbers.

Against v2.1.0:
The test prints the same output twice (`trim: false` is ignored).  The output is `"1  2  "` - both spaces before the '1' were removed.  If color terminal is disabled the spaces after the '2' are also removed.

Against v3.0.1:
The first line prints with a single space between the numbers, and if color is enabled a single space after the numbers.
The second line prints the original string if color is enabled, if color is disabled it prints an extra space before the string (3 spaces total before the '1').

This was found when trying to update cliui to use v3.0.1.  I don't know what the correct behavior should be.

### LINKED ISSUE #25: Off by one if trimming is disabled
If trimming is disabled, and you're wrapping a text a say length 3, and there's a whitespace right where the wrap should occur, the whitespace remains and the line break is appended to it. This results in the line being one char too long:

```js
console.log(JSON.stringify(trim('foo bar', 3)))                // => "foo\nbar"
console.log(JSON.stringify(trim('foo bar', 3, {trim: false}))) // => "foo \nbar"
```

### LINKED ISSUE #26: Incorrect leading spaces
with version 2.3.0:

```js
// 1 leading space
require('wrap-ansi')(' a ', process.stdout.columns, {trim: false})
```

Out:

```js
// 2 leading spaces
'  a '
```

### LINKED ISSUE #27: leading space removed when line starts with ansi escape
```js
const chalk = require('chalk');
const wrapAnsi = require('wrap-ansi');

const s = chalk.bgGreen(` ${chalk.black('OK')} `);
console.log(s);
console.log(wrapAnsi(s, 100, { trim: false }));
```

screen shot 2018-03-27 at 1 34 18 pm

### PR DESCRIPTION
**Pull request by stroncium**
Added tests, fixed incorrect treatment of rows which masked problem with tokenizer to proper way to treat tokens.

---

Fixes #23 
Fixes #24 
Fixes #25 
Fixes #26 
Fixes #27

### CODE REVIEW

**Comment by stroncium** [comment]
Turned out, #23 was depending on both #26 and #25(which also fixes #27), so I merged them all into one PR.

**Comment by stroncium** [comment]
Proper tests for #24 (part about leading spaces) require previous fixes in this PR, so I merged this fix here too.

**Comment by vadimdemedes** [comment]
Hey @stroncium, great work! Would you be able to copy test cases from https://github.com/chalk/wrap-ansi/pull/29/files#diff-1dd241c4cd3fd1dd89c570cee98b79dd into your PR to verify your fixes cover more stuff, so that I can close my PR?

**Comment by stroncium** [comment]
@vadimdemedes Most of them were already there, added remaining except this one: 
```
test('trim beginning of string if it starts with a space and not wrapped into background color escape', t => {
	const res = t.is(m(chalk.green(' hello '), 10, {hard: true, trim: false});
	t.is(res, chalk.green('hello '));
});
```
as I do believe that there is a mistake and it shouldn't be trimmed with `trim:false`.

**Comment by vadimdemedes** [comment]
Hey @stroncium, PR works great overall, there's only one issue I was able to find:

```js
const chalk = require('chalk')
const figures = require('figures')
const wrapAnsi = require('.')

const str = [
	`${chalk.green('?')} ${chalk.bold('select packages to update')}`,
	'',
	`${chalk.yellow('other')}`,
	`${figures.pointer} ${figures.circle} standard-version ${chalk.green('devDep')} ${chalk.bold('MISSING > 5.0.0')} ${chalk.blue('https://github.com/conventional-changelog/standard-version#readme')}`,
	''
].join('\n')

console.log(wrapAnsi(str, 64, {hard: true, trim: false}))
```

Produces the following output:

cleanshot 2019-02-28 at 22 36 14 2x

Link is moved over to the next line, instead of being wrapped as well. Here's the expected output:

cleanshot 2019-02-28 at 22 37 08 2x

Would you be able to look into it?

**Comment by stroncium** [comment]
@vadimdemedes It actually isn't a regression, and it was there before and this behavior is locked in testcases. It boils down to following expectation failing:
```
t.is(m('AAA WWWWWWWW', 7, {hard: true, trim: false}), 'AAA WWW\nWWWWW'); // produces 'AAA \nWWWWWWW\nW'
```
// CC @sindresorhus 
However, I looked into it and it actually seems to make more sense to do it that way. So I've implemented a simple heuristics on how to break words longer than columns in hard mode(minimizing number of breaks) using which would probably be a good idea.
It broke test `breaks strings longer than "cols" characters`(line 53) in part of exact breakdown of strings, so I propose to change it
Old expectation:
```
...
fox
jumpe
d
over
...
```

New expectation:
```
fox j
umped
over
```
Arguably, in this particular case neither option is looking quite pretty, but for real life purposes it should work good, and it fixes the problem stated above for example.

**Comment by vadimdemedes** [comment]
Works great, awesome work @stroncium!

**Comment by sindresorhus** [comment]
@stroncium Yes, the change makes sense to me.

**Comment by sindresorhus** [comment]
Really great work on this, @stroncium 🙌

**Pull request merged**
